name: BuildFFA
version: ${version}
main: de.florianreuth.buildffa.BuildFFA
description: ${description}
authors: [ EnZaXD, leycm, yyuh, Riesenrad ]
website: https://github.com/florianreuth/build-ffa
api-version: '1.21'

commands:
  kit:
    description: Select or list kits
    usage: /kit [name|list]
  buildffa:
    description: BuildFFA admin commands
    usage: /buildffa <reload|setspawn|info|buildmode>
    permission: buildffa.admin
  stats:
    description: Show BuildFFA stats
    usage: /stats [player]
  gadget:
    description: Select or list gadgets
    usage: /gadget [name|list]

permissions:
  buildffa.admin:
    default: op
  buildffa.kit.archer:
    default: true
  buildffa.kit.builder:
    default: true
  buildffa.kit.tank:
    default: true
  buildffa.kit.duelist:
    default: true
  buildffa.kit.rogue:
    default: true
  buildffa.kit.raider:
    default: true
  buildffa.kit.bruiser:
    default: true
  buildffa.gadget.healwand:
    default: true
  buildffa.gadget.leapfeather:
    default: true
  buildffa.gadget.fireball:
    default: true
  buildffa.gadget.dashboots:
    default: true
  buildffa.gadget.blinkpearl:
    default: true
  buildffa.gadget.shockcore:
    default: true
